### ISSUE TITLE
Blend file shape names to ShapeNet name mapping

### ISSUE THREAD

**Issue by nihalsid** [keunhong/photoshape#16]
Hi,

Awesome work! I was wondering if you can provide a mapping between the shapes in the ShapeNet chair dataset to the original ShapeNet chair names.

Thanks!

**Comment by keunhong** [comment]
You should be able to link them using the `source_id` field in the JSON filed: https://github.com/keunhong/photoshape#shapesjson

**Comment by nihalsid** [comment]
Thanks a lot!
