### ISSUE TITLE
Unable to clone brender

### ISSUE THREAD

**Issue by hjwdzh** [keunhong/photoshape#2]
$ git clone --recurse-submodules https://github.com/keunhong/photoshape
Cloning into 'photoshape'...
remote: Enumerating objects: 427, done.
remote: Counting objects: 100% (427/427), done.
remote: Compressing objects: 100% (353/353), done.
remote: Total 427 (delta 84), reused 399 (delta 60), pack-reused 0
Receiving objects: 100% (427/427), 54.72 MiB | 3.90 MiB/s, done.
Resolving deltas: 100% (84/84), done.
Checking connectivity... done.
Submodule 'thirdparty/brender' (git@github.com:keunhong/brender.git) registered for path 'thirdparty/brender'
Submodule 'thirdparty/kitnn' (git@github.com:keunhong/kitnn.git) registered for path 'thirdparty/kitnn'
Submodule 'thirdparty/rendkit' (git@github.com:keunhong/rendkit.git) registered for path 'thirdparty/rendkit'
Submodule 'thirdparty/siftflow' (git@github.com:keunhong/siftflow.git) registered for path 'thirdparty/siftflow'
Submodule 'thirdparty/toolbox' (git@github.com:keunhong/toolbox.git) registered for path 'thirdparty/toolbox'
Submodule 'thirdparty/vispy' (git@github.com:keunhong/vispy.git) registered for path 'thirdparty/vispy'
Cloning into 'thirdparty/brender'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:keunhong/brender.git' into submodule path 'thirdparty/brender' failed

**Comment by keunhong** [comment]
I think you can fix this one of two ways:

1. [Register your SSH public key with GitHub](https://help.github.com/articles/connecting-to-github-with-ssh/).
2. Replace all the SSH submodule URLs with HTTPS URLs with a command line `perl -i -p -e 's|git@(.*?):|https://\1/|g' .gitmodules`

**Comment by hjwdzh** [comment]
Thanks. It works.
