### ISSUE TITLE
Data Parser

### ISSUE THREAD

**Issue by hjwdzh** [keunhong/photoshape#3]
First, it's an impressive work!

Can you share more details of how to parse blend files you provided. For example, where can I find the script to generate the blend file / read it and get model/material/lighting information?

Additionally, I tried to render the blend file directly but there seems to be no light. May I know how I should render the images from the blend file correctly?

**Comment by hjwdzh** [comment]
Would be nice if you also can guide me how I should relate the materials in blend file to the materials in the JSON.

**Comment by keunhong** [comment]
Hi Jingwei,

Thank you for your kind words. The scripts I used to generate the blend files can be found [here](https://github.com/keunhong/photoshape/tree/master/src/terial/classifier/rendering). [This script](https://github.com/keunhong/photoshape/blob/master/src/terial/classifier/rendering/create_blend_file.py) takes one of the inference json files and creates the blend file.

Unfortunately the only way to "parse" the blend files is to load them into Blender (using the blender python runtime or the bpy module and read the [bpy.data](https://docs.blender.org/api/blender_python_api_2_75_0/bpy.data.html) blocks.

That's odd, I believe I packed the lighting information into the blend file (it's a single environment map). I'll take a look and get back to you here.

I'll draft up some documentation on mapping the JSON to what's in the blend files.

Thanks!
Keunhong

**Comment by hjwdzh** [comment]
Hi Keunhong,

Maybe I should describe the rendering issue with more details.

I believe the problem is from the material since the material preview in blender shows pure black color. I can see how texture images are related to define the material in the node editor, but the problem could come from the shader, which is shown as "undefined" instead of "standard BSDF" in cycles renderer. 

Should I use cycles to render it? I see that you mention that you use vispy. Is that an plugin to blender that I should use?

Thanks!
Jingwei

**Comment by hjwdzh** [comment]
I believe I have the right solution now. As I use python to log the material nodes, it's called principled BRDF, which is shown as undefined in older blender version. The minimum requirement Blender version for the principled BRDF is 2.79 :) Maybe other people also want to know it.

**Comment by keunhong** [comment]
Sorry for the late response. You're definitely right that there's a minimum Blender version required, I'll make sure I document this.
