### ISSUE TITLE
An issue in src/terial/shapes/generate_alignment_rends.py

### ISSUE THREAD

**Issue by ZhizhuoZhang** [keunhong/photoshape#4]
Hi,Keunhong!
In line 48,how can get the radiance map rnl.cross.exr?

**Comment by keunhong** [comment]
Hi Zhizhuo,

I've uploaded the cross format environment maps here: https://github.com/keunhong/photoshape/releases/download/0.1/rendkit-envmaps.zip

But if you're trying to compute the HOG features for the shapes, then I have a precomputed archive in PyTorch format [here](https://drive.google.com/file/d/11fAxm4ZER-geKFoxnvaE-RbRU32ZuNo-/view). It's used to compute pairs in this code: https://github.com/keunhong/photoshape/blob/master/src/terial/pairs/compute_pairs.py#L189

**Comment by ZhizhuoZhang** [comment]
Thanks a lot.I really appreciate it.
